name: Go

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20"]
    steps:
      - name: Updating ...
        run: sudo apt-get -qq update

      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go build (source)
        run: go build ./...

      - name: Go build (tests)
        run: go test -v ./...

      - name: Go vet
        run: go get -v ./...
