name: Lint

on: pull_request

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download
      - name: Run commitsar
        uses: aevea/commitsar@v0.20.2
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          # https://github.com/golangci/golangci-lint-action/issues/135
          skip-pkg-cache: true
  lint-language:
    name: Lint language
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
